# Generated by Django 5.0.4 on 2024-04-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("author", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
                ("likes", models.IntegerField(default=0)),
                ("image", models.URLField(blank=True)),
            ],
        ),
    ]
